import { defineConfig, lazyPlugins } from "vite-plus";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import { cloudflare } from "@cloudflare/vite-plugin";

export default defineConfig(({ mode }) => ({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    // generated by @tanstack/router-plugin on every server start
    ignorePatterns: ["src/routeTree.gen.ts"],
  },
  lint: {
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
  },
  plugins: lazyPlugins(() => {
    const plugins = [
      tanstackRouter({
        target: "react",
        autoCodeSplitting: true,
      }),
      react(),
    ];
    // cloudflare() owns a vite server for dev/preview (single-process client +
    // worker); vitest (mode "test") creates its own server and would collide
    if (mode !== "test") {
      // runs server/worker.mjs (signaling WebSocket + Room Durable Object)
      // inside the Vite dev/preview server — one process for client and backend
      plugins.push(cloudflare());
    }
    return plugins;
  }),
  server: {
    host: true,
  },
  build: {
    target: "es2022",
  },
}));
