import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { defineConfig, lazyPlugins } from "vite-plus";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import { cloudflare } from "@cloudflare/vite-plugin";

// og.png is referenced from social meta with a content-hash query (?v=…) so
// every deploy that changes the image also changes its URL — chat-app
// crawlers (Facebook/WhatsApp) otherwise cache the first preview forever.
const ogHash = createHash("sha256")
  .update(readFileSync(new URL("./public/og.png", import.meta.url)))
  .digest("hex")
  .slice(0, 12);

// canonical origin baked into the static home page's social tags (set
// PUBLIC_ORIGIN when building behind a custom domain). Room invites don't
// need this — the worker rewrites them per request origin at serve time.
const PUBLIC_ORIGIN = (process.env.PUBLIC_ORIGIN ?? "https://maishare.panudet.dev")
  .trim()
  .replace(/\/+$/, "");

/** bake absolute, cache-busted social URLs into the static home page —
 * crawlers ignore relative og:image and cache the first URL forever */
function ogAbsoluteUrls(): import("vite-plus").Plugin {
  return {
    name: "og-absolute-urls",
    transformIndexHtml(html) {
      return html
        .replaceAll('content="/og.png"', `content="${PUBLIC_ORIGIN}/og.png?v=${ogHash}"`)
        .replace(
          /(<meta property="og:site_name" content="maishare" \/>)/,
          `$1\n    <meta property="og:url" content="${PUBLIC_ORIGIN}/" />`,
        );
    },
  };
}

export default defineConfig(({ mode }) => ({
  define: {
    __OG_ASSET_VERSION__: JSON.stringify(ogHash),
  },
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    // generated by @tanstack/router-plugin on every server start; vendor is
    // the wasm-bindgen build output of katgpt-magika-wasm; .playground is
    // per-session scratch space (venvs, renders, generated audio/html)
    ignorePatterns: ["src/routeTree.gen.ts", "vendor", ".playground"],
  },
  lint: {
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
    ignorePatterns: ["src/routeTree.gen.ts", "vendor", ".playground"],
  },
  plugins: lazyPlugins(() => {
    const plugins = [
      ogAbsoluteUrls(),
      tanstackRouter({
        target: "react",
        autoCodeSplitting: true,
      }),
      react(),
    ];
    // cloudflare() owns a vite server for dev/preview (single-process client +
    // worker); vitest (mode "test") creates its own server and would collide
    if (mode !== "test") {
      // runs server/worker.mjs (signaling WebSocket + Room Durable Object)
      // inside the Vite dev/preview server — one process for client and backend
      plugins.push(cloudflare());
    }
    return plugins;
  }),
  // SEC-10: dev/preview bind localhost by default — exposing the worker (and
  // its forwarded-header identity trust) to the LAN stays the explicit --host
  // opt-in the README documents, never a silent config default.
  build: {
    target: "es2022",
  },
}));
