// Post-build step for the PWA: scans dist/client and emits a service worker
// (dist/client/sw.js) that precaches the whole app shell, so an installed PWA
// boots with no network. Runs after `vp build` (see package.json "build").
//
//   vp build && node scripts/pwa-build.mjs
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, posix, resolve } from "node:path";

const ROOT = resolve(process.argv[2] ?? "dist/client");

function walk(dir, prefix = "") {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    const url = posix.join("/", prefix, entry);
    if (statSync(p).isDirectory()) out.push(...walk(p, url));
    else out.push(url);
  }
  return out;
}

// everything except the worker we emit, source maps (no value offline) and
// dotfiles (.assetsignore etc.) — URLs must be root-absolute or the SW would
// resolve them relative to its own location and fail to install.
// /index.html is excluded on purpose: the asset server redirects it to "/" and
// Chrome refuses redirected responses handed to respondWith() — the app shell
// is precached under "/" instead, which is also the SPA fallback for every
// navigation.
const files = walk(ROOT).filter(
  (f) =>
    f !== "/sw.js" &&
    f !== "/index.html" &&
    !f.endsWith(".map") &&
    !posix.basename(f).startsWith("."),
);
const precache = [
  { url: "/", revision: "" },
  ...files.map((url) => ({
    url,
    revision: createHash("sha256")
      .update(readFileSync(join(ROOT, url)))
      .digest("hex")
      .slice(0, 16),
  })),
];

// The worker is a plain JS file written at build time (no bundler): precache
// the hashed assets cache-first and serve everything else stale-while-
// revalidate, with the "/" app shell as the offline fallback for navigations.
const sw = `// generated by scripts/pwa-build.mjs — do not edit
const VERSION = "maishare-${new Date()
  .toISOString()
  .replace(/[^0-9a-z]/g, "")
  .slice(0, 14)}";
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches
      .open(VERSION)
      .then((c) => Promise.all(PRECACHE.map((x) => c.add(new Request(x.url, { cache: "reload" })))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

async function staleWhileRevalidate(key, request) {
  const cache = await caches.open(VERSION);
  const cached = await cache.match(key);
  const refresh = fetch(request)
    .then((res) => {
      if (res && res.ok) cache.put(key, res.clone());
      return res;
    })
    .catch(() => null);
  return cached || (await refresh) || Response.error();
}

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  // signaling and discovery are live-only: never served from cache
  if (url.pathname === "/ws" || url.pathname.startsWith("/api/")) return;
  if (req.mode === "navigate") {
    // never key a cache entry by the navigation URL: routes carry secrets in
    // their query strings (?k=) and every room's shell differs (the worker
    // rewrites its og tags) — so go network-first for a fresh per-route shell,
    // refresh the shared "/" shell in passing for offline boots, and fall back
    // to that shell when offline
    e.respondWith(
      fetch(req)
        .then((res) => {
          if (!res || !res.ok) return res || Response.error();
          return caches.open(VERSION).then((c) => {
            c.put("/", res.clone());
            return res;
          });
        })
        .catch(() => caches.match("/").then((r) => r || fetch(req))),
    );
    return;
  }
  e.respondWith(staleWhileRevalidate(url.pathname, req));
});
`;

writeFileSync(join(ROOT, "sw.js"), sw);
console.log(`sw.js: precaching ${precache.length} files (app shell works offline)`);
